-- PostgreSQL does not support removing enum values once added.
-- To fully revert, recreate the type without the new variants:
--
--   ALTER TYPE skill_domain RENAME TO skill_domain_old;
--   CREATE TYPE skill_domain AS ENUM (
--     'combat','strategy','intelligence','information_technology',
--     'human_resources','finance','communications','administration',
--     'engineering','medical','management','leadership','joint_operations'
--   );
--   ALTER TABLE skills     ALTER COLUMN domain     TYPE skill_domain USING domain::text::skill_domain;
--   ALTER TABLE capabilities ALTER COLUMN domain   TYPE skill_domain USING domain::text::skill_domain;
--   ALTER TABLE requirements ALTER COLUMN domain   TYPE skill_domain USING domain::text::skill_domain;
--   ALTER TABLE tasks        ALTER COLUMN domain   TYPE skill_domain USING domain::text::skill_domain;
--   ALTER TABLE works        ALTER COLUMN domain   TYPE skill_domain USING domain::text::skill_domain;
--   ALTER TABLE org_tiers    ALTER COLUMN primary_domain TYPE skill_domain USING primary_domain::text::skill_domain;
--   ALTER TABLE teams        ALTER COLUMN primary_domain TYPE skill_domain USING primary_domain::text::skill_domain;
--   DROP TYPE skill_domain_old;
--
-- Only safe after migrating all rows away from the new variant values.
